<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FrameGrabber</AssemblyName>
    <RootNamespace>FrameGrabber</RootNamespace>
    <ApplicationIcon>assets\FrameGrabber.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="assets\FrameGrabber.ico" />
  </ItemGroup>
</Project>
