using System.Globalization;
using System.IO;
using System.Text.Json;
using System.Collections.ObjectModel;
using System.Windows;
using System.Windows.Input;
using System.Windows.Media.Imaging;
using System.Windows.Media;
using System.Windows.Controls.Primitives;
using Forms = System.Windows.Forms;

namespace FrameGrabber;
public partial class MainWindow : Window
{
    private readonly MediaService media = new(); private VideoInfo? video; private string folder = Environment.GetFolderPath(Environment.SpecialFolder.MyPictures); private bool suppress; private bool suppressChapterSelection; private readonly ObservableCollection<QueueItem> queue = new();
    public MainWindow() { InitializeComponent(); QueueList.ItemsSource = queue; Timeline.PreviewMouseLeftButtonDown += Timeline_Click; SetChapterControlsVisibility(false); foreach (var button in FindVisualChildren<System.Windows.Controls.Button>(this)) { if (button.Content?.ToString() == "Import queue") button.Content = "Import"; if (button.Content?.ToString() == "Save queue") button.Content = "Export"; } var saved = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "FrameGrabber", "export-folder.txt"); if (File.Exists(saved)) folder = File.ReadAllText(saved).Trim(); FolderText.Text = folder; }
    private void Window_DragOver(object s, System.Windows.DragEventArgs e) => e.Effects = e.Data.GetDataPresent(System.Windows.DataFormats.FileDrop) ? System.Windows.DragDropEffects.Copy : System.Windows.DragDropEffects.None;
    private void Window_Drop(object s, System.Windows.DragEventArgs e) { if (e.Data.GetData(System.Windows.DataFormats.FileDrop) is string[] files && files.Length > 0) LoadVideo(files[0]); }
    private void Browse_Click(object s, RoutedEventArgs e) { using var d = new Forms.OpenFileDialog { Filter = "Video files|*.mkv;*.mp4;*.mov;*.webm;*.avi;*.m4v;*.ts|All files|*.*" }; if (d.ShowDialog() == Forms.DialogResult.OK) LoadVideo(d.FileName); }
    private async void LoadVideo(string path) { try { StatusText.Text = "Reading video metadata…"; video = await Task.Run(() => media.Probe(path)); FileNameText.Text = video.FileName; FilePathText.Text = path; ResolutionText.Text = $"{video.Width} × {video.Height}"; CodecText.Text = video.Codec; DepthText.Text = $"{video.BitDepth}-bit"; DurationText.Text = FormatFrame(video.Duration); Timeline.Maximum = Math.Max(video.Duration.TotalSeconds, 0.001); Timeline.Value = 0; ChapterPicker.ItemsSource = video.Chapters; SetChapterControlsVisibility(video.Chapters.Count > 0); ExportButton.IsEnabled = true; HdrBadge.Visibility = video.IsHdr ? Visibility.Visible : Visibility.Collapsed; HdrText.Text = video.IsDolbyVision ? "◆ Dolby Vision · tone-mapped to SDR" : "◆ HDR · tone-mapped to SDR"; ColorText.Text = $"{(string.IsNullOrWhiteSpace(video.ColorSpace) ? "Color space unknown" : video.ColorSpace)}  ·  {(string.IsNullOrWhiteSpace(video.Transfer) ? "transfer unknown" : video.Transfer)}  ·  {video.Primaries}"; StatusText.Text = video.IsHdr ? "HDR preview active — exports are tone-mapped to SDR" : "Video loaded — choose a moment to export"; await UpdatePreview(); } catch (Exception ex) { StatusText.Text = "Could not read video. Make sure ffmpeg and ffprobe are installed and on PATH."; System.Windows.MessageBox.Show(ex.Message, "FrameGrabber", MessageBoxButton.OK, MessageBoxImage.Warning); } }
    private void Timeline_ValueChanged(object s, RoutedPropertyChangedEventArgs<double> e) { if (video is null || suppress || !IsLoaded) return; CurrentTimeText.Text = FormatFrame(TimeSpan.FromSeconds(e.NewValue)); TimeInput.Text = CurrentTimeText.Text; SyncChapterPicker(e.NewValue); }
    private async void Timeline_Click(object? sender, MouseButtonEventArgs e) { if (video is null || e.OriginalSource is Thumb) return; var point = e.GetPosition(Timeline); var ratio = Math.Clamp(point.X / Math.Max(Timeline.ActualWidth, 1), 0, 1); e.Handled = true; await GoTo(TimeSpan.FromSeconds(ratio * video.Duration.TotalSeconds)); }
    private async void Timeline_PreviewMouseUp(object s, MouseButtonEventArgs e) { await UpdatePreview(); }
    private async void TimeInput_KeyDown(object s, System.Windows.Input.KeyEventArgs e) { if (e.Key != Key.Enter || video is null) return; if (TryParse(TimeInput.Text, out var t)) { suppress = true; Timeline.Value = Math.Clamp(t.TotalSeconds, 0, video.Duration.TotalSeconds); suppress = false; CurrentTimeText.Text = FormatFrame(TimeSpan.FromSeconds(Timeline.Value)); TimeInput.Text = CurrentTimeText.Text; SyncChapterPicker(Timeline.Value); await UpdatePreview(); } }
    private async Task UpdatePreview() { var currentVideo = video; if (currentVideo is null) return; var seconds = Timeline.Value; try { StatusText.Text = "Rendering preview…"; var tmp = Path.Combine(Path.GetTempPath(), $"framegrabber-preview-{Guid.NewGuid():N}.png"); await Task.Run(() => media.Extract(currentVideo.FilePath, TimeSpan.FromSeconds(seconds), tmp, 900, currentVideo.IsHdr)); if (!File.Exists(tmp) || new FileInfo(tmp).Length == 0) throw new InvalidOperationException("FFmpeg did not create a preview image."); var image = new BitmapImage(); image.BeginInit(); image.CacheOption = BitmapCacheOption.OnLoad; image.StreamSource = new MemoryStream(await File.ReadAllBytesAsync(tmp)); image.EndInit(); image.Freeze(); PreviewImage.Source = image; PreviewImage.Visibility = Visibility.Visible; DropZone.Background = System.Windows.Media.Brushes.Black; StatusText.Text = currentVideo.IsHdr ? "Preview tone-mapped to SDR" : "Preview ready"; } catch (Exception ex) { PreviewImage.Visibility = Visibility.Collapsed; StatusText.Text = $"Preview unavailable: {ex.Message}"; } }
    private async void Export_Click(object s, RoutedEventArgs e) { if (video is null) return; try { Directory.CreateDirectory(folder); var t = TimeSpan.FromSeconds(Timeline.Value); var name = $"{Path.GetFileNameWithoutExtension(video.FileName)}-{FormatFileTime(t)}.png"; var output = Path.Combine(folder, name); await Task.Run(() => media.Extract(video.FilePath, t, output, null, video.IsHdr)); StatusText.Text = $"Exported {name}"; } catch (Exception ex) { System.Windows.MessageBox.Show(ex.Message, "Export failed", MessageBoxButton.OK, MessageBoxImage.Error); } }
    private async Task GoTo(TimeSpan time) { if (video is null) return; suppress = true; Timeline.Value = Math.Clamp(time.TotalSeconds, 0, video.Duration.TotalSeconds); suppress = false; CurrentTimeText.Text = FormatFrame(TimeSpan.FromSeconds(Timeline.Value)); TimeInput.Text = CurrentTimeText.Text; SyncChapterPicker(Timeline.Value); await UpdatePreview(); }
    private async void FrameBack_Click(object s, RoutedEventArgs e) => await GoTo(TimeSpan.FromSeconds(Timeline.Value - 1 / Math.Max(video?.FrameRate ?? 24, 1)));
    private async void FrameForward_Click(object s, RoutedEventArgs e) => await GoTo(TimeSpan.FromSeconds(Timeline.Value + 1 / Math.Max(video?.FrameRate ?? 24, 1)));
    private async void Rewind_Click(object s, RoutedEventArgs e) => await GoTo(TimeSpan.FromSeconds(Timeline.Value - 5));
    private async void Rewind1_Click(object s, RoutedEventArgs e) => await GoTo(TimeSpan.FromSeconds(Timeline.Value - 1));
    private async void FastForward1_Click(object s, RoutedEventArgs e) => await GoTo(TimeSpan.FromSeconds(Timeline.Value + 1));
    private async void FastForward_Click(object s, RoutedEventArgs e) => await GoTo(TimeSpan.FromSeconds(Timeline.Value + 5));
    private async void ChapterBack_Click(object s, RoutedEventArgs e) { if (video is null || video.Chapters.Count == 0) return; var i = video.Chapters.Select((c, n) => (c, n)).LastOrDefault(x => x.c.Start.TotalSeconds < Timeline.Value - 0.5).n; await GoTo(video.Chapters[Math.Clamp(i, 0, video.Chapters.Count - 1)].Start); }
    private async void ChapterForward_Click(object s, RoutedEventArgs e) { if (video is null || video.Chapters.Count == 0) return; var c = video.Chapters.FirstOrDefault(x => x.Start.TotalSeconds > Timeline.Value + 0.5); await GoTo(c?.Start ?? video.Chapters[^1].Start); }
    private async void ChapterPicker_SelectionChanged(object s, System.Windows.Controls.SelectionChangedEventArgs e) { if (suppressChapterSelection || ChapterPicker.SelectedItem is not ChapterInfo c || !IsLoaded) return; await GoTo(c.Start); }
    private void SyncChapterPicker(double seconds) { if (video is null || video.Chapters.Count == 0) return; var index = video.Chapters.Select((chapter, i) => (chapter, i)).Where(x => x.chapter.Start.TotalSeconds <= seconds + 0.001).Select(x => x.i).DefaultIfEmpty(0).Last(); if (ChapterPicker.SelectedIndex == index) return; suppressChapterSelection = true; ChapterPicker.SelectedIndex = index; suppressChapterSelection = false; }
    private void SetChapterControlsVisibility(bool visible) { foreach (var control in FindVisualChildren<FrameworkElement>(this)) if (control == ChapterPicker || (control is System.Windows.Controls.Button b && b.Content?.ToString()?.Contains("Chapter", StringComparison.OrdinalIgnoreCase) == true)) control.Visibility = visible ? Visibility.Visible : Visibility.Collapsed; }
    private static IEnumerable<T> FindVisualChildren<T>(DependencyObject root) where T : DependencyObject { if (root is null) yield break; for (var i = 0; i < VisualTreeHelper.GetChildrenCount(root); i++) { var child = VisualTreeHelper.GetChild(root, i); if (child is T match) yield return match; foreach (var nested in FindVisualChildren<T>(child)) yield return nested; } }
    private void AddQueue_Click(object s, RoutedEventArgs e) { if (video is not null) queue.Add(new QueueItem(FormatFrame(TimeSpan.FromSeconds(Timeline.Value)))); }
    private async void QueuePreview_Click(object s, RoutedEventArgs e) { if (senderTime(s) is TimeSpan t) await GoTo(t); }
    private TimeSpan? senderTime(object s) { if (((FrameworkElement)s).Tag is QueueItem q && TryParse(q.Timecode, out var t) && video is not null) return TimeSpan.FromSeconds(Math.Clamp(t.TotalSeconds, 0, video.Duration.TotalSeconds)); return null; }
    private void QueueRemove_Click(object s, RoutedEventArgs e) { if (((FrameworkElement)s).Tag is QueueItem q) queue.Remove(q); }
    private void QueueUp_Click(object s, RoutedEventArgs e) { if (((FrameworkElement)s).Tag is QueueItem q) { var i = queue.IndexOf(q); if (i > 0) queue.Move(i, i - 1); } }
    private void QueueDown_Click(object s, RoutedEventArgs e) { if (((FrameworkElement)s).Tag is QueueItem q) { var i = queue.IndexOf(q); if (i >= 0 && i < queue.Count - 1) queue.Move(i, i + 1); } }
    private void ClearQueue_Click(object s, RoutedEventArgs e) => queue.Clear();
    private void ExportQueue_Click(object s, RoutedEventArgs e) { var title = video is null ? "video" : Path.GetFileNameWithoutExtension(video.FileName); using var d = new Forms.SaveFileDialog { Filter = "FrameGrabber queue|*.json", FileName = $"{title}-framegrab.json" }; if (d.ShowDialog() == Forms.DialogResult.OK) File.WriteAllText(d.FileName, JsonSerializer.Serialize(new { Video = video?.FilePath, Timecodes = queue.Select(x => x.Timecode) }, new JsonSerializerOptions { WriteIndented = true })); }
    private void ImportQueue_Click(object s, RoutedEventArgs e) { using var d = new Forms.OpenFileDialog { Filter = "FrameGrabber queue|*.json" }; if (d.ShowDialog() != Forms.DialogResult.OK) return; try { using var doc = JsonDocument.Parse(File.ReadAllText(d.FileName)); var root = doc.RootElement; var source = root.TryGetProperty("Video", out var v) ? v.GetString() : null; if (!string.IsNullOrWhiteSpace(source) && File.Exists(source) && (video is null || !string.Equals(video.FilePath, source, StringComparison.OrdinalIgnoreCase))) { LoadVideo(source); } queue.Clear(); if (root.TryGetProperty("Timecodes", out var times)) foreach (var t in times.EnumerateArray()) if (t.GetString() is string tc) queue.Add(new QueueItem(tc)); } catch (Exception ex) { System.Windows.MessageBox.Show(ex.Message, "Queue import failed", MessageBoxButton.OK, MessageBoxImage.Warning); } }
    private async void ExportAll_Click(object s, RoutedEventArgs e) { if (video is null || queue.Count == 0) return; try { Directory.CreateDirectory(folder); var valid = queue.Select(q => (q, ok: TryParse(q.Timecode, out var t), t)).Where(x => x.ok).ToList(); foreach (var item in valid) { var t = TimeSpan.FromSeconds(Math.Clamp(item.t.TotalSeconds, 0, video.Duration.TotalSeconds)); var name = $"{Path.GetFileNameWithoutExtension(video.FileName)}-{FormatFileTime(t)}.png"; await Task.Run(() => media.Extract(video.FilePath, t, Path.Combine(folder, name), null, video.IsHdr)); } StatusText.Text = $"Exported {valid.Count} queued frame(s)"; } catch (Exception ex) { System.Windows.MessageBox.Show(ex.Message, "Batch export failed", MessageBoxButton.OK, MessageBoxImage.Error); } }
    private void Preferences_Click(object s, RoutedEventArgs e) { using var d = new Forms.FolderBrowserDialog { Description = "Choose your default frame export folder", SelectedPath = folder, UseDescriptionForTitle = true }; if (d.ShowDialog() == Forms.DialogResult.OK) { folder = d.SelectedPath; FolderText.Text = folder; var settings = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "FrameGrabber"); Directory.CreateDirectory(settings); File.WriteAllText(Path.Combine(settings, "export-folder.txt"), folder); } }
    private string FormatFrame(TimeSpan t) { var fps = Math.Max(video?.FrameRate ?? 24, 1); var wholeFps = Math.Max((int)Math.Round(fps), 1); var frame = (int)Math.Round(t.TotalSeconds * fps, MidpointRounding.AwayFromZero); var seconds = frame / wholeFps; var frames = frame % wholeFps; return $"{seconds / 3600:00}:{seconds / 60 % 60:00}:{seconds % 60:00}.{frames:00}"; }
    private string FormatFileTime(TimeSpan t) => FormatFrame(t).Replace(':','-');
    private bool TryParse(string value, out TimeSpan time) { time = TimeSpan.Zero; var p = value.Split(':'); if (p.Length == 3 && int.TryParse(p[0], out var h) && int.TryParse(p[1], out var m)) { var sf = p[2].Split('.'); if (sf.Length == 2 && int.TryParse(sf[0], out var sec) && int.TryParse(sf[1], out var fr)) { time = TimeSpan.FromSeconds(h * 3600 + m * 60 + sec + fr / Math.Max(video?.FrameRate ?? 24, 1)); return true; } } if (double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out var seconds)) { time = TimeSpan.FromSeconds(seconds); return true; } return TimeSpan.TryParse(value, CultureInfo.InvariantCulture, out time); }
}

