using System.Globalization;
using System.IO;
using System.Windows;
using System.Windows.Input;
using System.Windows.Media.Imaging;
using Forms = System.Windows.Forms;

namespace FrameGrabber;
public partial class MainWindow : Window
{
    private readonly MediaService media = new(); private VideoInfo? video; private string folder = Environment.GetFolderPath(Environment.SpecialFolder.MyPictures); private bool suppress;
    public MainWindow() { InitializeComponent(); var saved = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "FrameGrabber", "export-folder.txt"); if (File.Exists(saved)) folder = File.ReadAllText(saved).Trim(); FolderText.Text = folder; }
    private void Window_DragOver(object s, System.Windows.DragEventArgs e) => e.Effects = e.Data.GetDataPresent(System.Windows.DataFormats.FileDrop) ? System.Windows.DragDropEffects.Copy : System.Windows.DragDropEffects.None;
    private void Window_Drop(object s, System.Windows.DragEventArgs e) { if (e.Data.GetData(System.Windows.DataFormats.FileDrop) is string[] files && files.Length > 0) LoadVideo(files[0]); }
    private void Browse_Click(object s, RoutedEventArgs e) { using var d = new Forms.OpenFileDialog { Filter = "Video files|*.mkv;*.mp4;*.mov;*.webm;*.avi;*.m4v;*.ts|All files|*.*" }; if (d.ShowDialog() == Forms.DialogResult.OK) LoadVideo(d.FileName); }
    private async void LoadVideo(string path) { try { StatusText.Text = "Reading video metadata…"; video = await Task.Run(() => media.Probe(path)); FileNameText.Text = video.FileName; FilePathText.Text = path; ResolutionText.Text = $"{video.Width} × {video.Height}"; CodecText.Text = video.Codec; DepthText.Text = $"{video.BitDepth}-bit"; DurationText.Text = Format(video.Duration); Timeline.Maximum = Math.Max(video.Duration.TotalSeconds, 0.001); Timeline.Value = 0; ExportButton.IsEnabled = true; HdrBadge.Visibility = video.IsHdr ? Visibility.Visible : Visibility.Collapsed; HdrText.Text = video.IsDolbyVision ? "◆ Dolby Vision · tone-mapped to SDR" : "◆ HDR · tone-mapped to SDR"; ColorText.Text = $"{(string.IsNullOrWhiteSpace(video.ColorSpace) ? "Color space unknown" : video.ColorSpace)}  ·  {(string.IsNullOrWhiteSpace(video.Transfer) ? "transfer unknown" : video.Transfer)}  ·  {video.Primaries}"; StatusText.Text = video.IsHdr ? "HDR preview active — exports are tone-mapped to SDR" : "Video loaded — choose a moment to export"; await UpdatePreview(); } catch (Exception ex) { StatusText.Text = "Could not read video. Make sure ffmpeg and ffprobe are installed and on PATH."; System.Windows.MessageBox.Show(ex.Message, "FrameGrabber", MessageBoxButton.OK, MessageBoxImage.Warning); } }
    private void Timeline_ValueChanged(object s, RoutedPropertyChangedEventArgs<double> e) { if (video is null || suppress || !IsLoaded) return; CurrentTimeText.Text = Format(TimeSpan.FromSeconds(e.NewValue)); TimeInput.Text = CurrentTimeText.Text; }
    private async void Timeline_PreviewMouseUp(object s, MouseButtonEventArgs e) { await UpdatePreview(); }
    private async void TimeInput_KeyDown(object s, System.Windows.Input.KeyEventArgs e) { if (e.Key != Key.Enter || video is null) return; if (TryParse(TimeInput.Text, out var t)) { suppress = true; Timeline.Value = Math.Clamp(t.TotalSeconds, 0, video.Duration.TotalSeconds); suppress = false; CurrentTimeText.Text = Format(t); await UpdatePreview(); } }
    private async Task UpdatePreview() { var currentVideo = video; if (currentVideo is null) return; var seconds = Timeline.Value; try { StatusText.Text = "Rendering preview…"; var tmp = Path.Combine(Path.GetTempPath(), $"framegrabber-preview-{Guid.NewGuid():N}.png"); await Task.Run(() => media.Extract(currentVideo.FilePath, TimeSpan.FromSeconds(seconds), tmp, 900, currentVideo.IsHdr)); if (!File.Exists(tmp) || new FileInfo(tmp).Length == 0) throw new InvalidOperationException("FFmpeg did not create a preview image."); var image = new BitmapImage(); image.BeginInit(); image.CacheOption = BitmapCacheOption.OnLoad; image.StreamSource = new MemoryStream(await File.ReadAllBytesAsync(tmp)); image.EndInit(); image.Freeze(); PreviewImage.Source = image; PreviewImage.Visibility = Visibility.Visible; DropZone.Background = System.Windows.Media.Brushes.Black; StatusText.Text = currentVideo.IsHdr ? "Preview tone-mapped to SDR" : "Preview ready"; } catch (Exception ex) { PreviewImage.Visibility = Visibility.Collapsed; StatusText.Text = $"Preview unavailable: {ex.Message}"; } }
    private async void Export_Click(object s, RoutedEventArgs e) { if (video is null) return; try { Directory.CreateDirectory(folder); var t = TimeSpan.FromSeconds(Timeline.Value); var name = $"{Path.GetFileNameWithoutExtension(video.FileName)}-{FormatFileTime(t)}.png"; var output = Path.Combine(folder, name); await Task.Run(() => media.Extract(video.FilePath, t, output, null, video.IsHdr)); StatusText.Text = $"Exported {name}"; } catch (Exception ex) { System.Windows.MessageBox.Show(ex.Message, "Export failed", MessageBoxButton.OK, MessageBoxImage.Error); } }
    private void Preferences_Click(object s, RoutedEventArgs e) { using var d = new Forms.FolderBrowserDialog { Description = "Choose your default frame export folder", SelectedPath = folder, UseDescriptionForTitle = true }; if (d.ShowDialog() == Forms.DialogResult.OK) { folder = d.SelectedPath; FolderText.Text = folder; var settings = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "FrameGrabber"); Directory.CreateDirectory(settings); File.WriteAllText(Path.Combine(settings, "export-folder.txt"), folder); } }
    private static string Format(TimeSpan t) => $"{(int)t.TotalHours:00}:{t.Minutes:00}:{t.Seconds:00}.{t.Milliseconds:000}"; private static string FormatFileTime(TimeSpan t) => Format(t).Replace(':','-');
    private static bool TryParse(string value, out TimeSpan time) { if (TimeSpan.TryParse(value, CultureInfo.InvariantCulture, out time)) return true; if (double.TryParse(value, out var seconds)) { time = TimeSpan.FromSeconds(seconds); return true; } return false; }
}

